@baseUrl = http://localhost:3000/api

###
# @name create user
POST {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU0NjgxNn0.f_VA_0nK2rnKBXD81hjCUTW3H38qGELgXQXK8tWrE_Y

{
    "id": "22323252325",
    "phoneNumber": "0631567899",
    "fullName": "user 3",
    "address": "address 3"
}

###
# @name Get all users

GET {{baseUrl}}/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU0NjgxNn0.f_VA_0nK2rnKBXD81hjCUTW3H38qGELgXQXK8tWrE_Y

###
# @name Get user by id

GET {{baseUrl}}/user/6364bef8d022442b874e59f7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU0NjgxNn0.f_VA_0nK2rnKBXD81hjCUTW3H38qGELgXQXK8tWrE_Y

###
# @name update user

PUT {{baseUrl}}/user/6364bef8d022442b874e59f7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU0NjgxNn0.f_VA_0nK2rnKBXD81hjCUTW3H38qGELgXQXK8tWrE_Y

{
    "fullName": "nguyen 1",
    "address": "hai phong"
}

###
# @name delete user

DELETE {{baseUrl}}/user/6364bef8d022442b874e59f7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU0NjgxNn0.f_VA_0nK2rnKBXD81hjCUTW3H38qGELgXQXK8tWrE_Y

###
# @name vaccinated 

POST {{baseUrl}}/user/vaccinated
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU0NjgxNn0.f_VA_0nK2rnKBXD81hjCUTW3H38qGELgXQXK8tWrE_Y

{
    "userId": "6364e460b63a5632f3507250",
    "vaccineId": "636b4f6e4570ca354a074002",
    "vaccineLotId": "636b4f6e4570ca354a074002"
}

###
# @name all place of user 

GET {{baseUrl}}/user/6364e460b63a5632f3507250/place
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU0NjgxNn0.f_VA_0nK2rnKBXD81hjCUTW3H38qGELgXQXK8tWrE_Y


###
# @name user checkin place 

POST {{baseUrl}}/user/checkin-place
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRlNDYwYjYzYTU2MzJmMzUwNzI1MCIsImlhdCI6MTY2NzU1NjQ0OH0.FGLRw_2Wu2iXW3L4rdDqC6Sh3YG0A48XKEM7OUudYeQ

{
    "placeId": "6364e4ed2f48fa34e7be8d4e"

}

###
# @name user all place checked in  

GET {{baseUrl}}/user/6364e460b63a5632f3507250/place-visited
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU0NjgxNn0.f_VA_0nK2rnKBXD81hjCUTW3H38qGELgXQXK8tWrE_Y
