@baseUrl = http://localhost:3000/api

###
# @name create vaccine lot
POST {{baseUrl}}/vaccine/lots
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2Nzk2NTE4OX0.bT-ChM7yy1RQtNgwcKU2um8EUoUEzQXErLrFD3ovhrk

{
    "name": "astrazeneca",
    "quantity":100000,
    "vaccineId":"636b2655d401a6306ea87676"
}


###
# @name Get all vaccine lots
GET {{baseUrl}}/vaccine/lots/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2Nzk2NTE4OX0.bT-ChM7yy1RQtNgwcKU2um8EUoUEzQXErLrFD3ovhrk


###
# @name Get vaccine lot by id

GET {{baseUrl}}/vaccine/lots/636b32770a98476390d2f757
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2Nzk2NTE4OX0.bT-ChM7yy1RQtNgwcKU2um8EUoUEzQXErLrFD3ovhrk


###
# @name update vaccine lot by id

PUT {{baseUrl}}/vaccine/lots/636b32770a98476390d2f757
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2Nzk2NTE4OX0.bT-ChM7yy1RQtNgwcKU2um8EUoUEzQXErLrFD3ovhrk

{
    "name": "Hayatt",
    "quantity": 200000
}


###
# @name Delete vaccine lots by id

DELETE {{baseUrl}}/vaccine/lots/636b32770a98476390d2f757
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2Nzk2NTE4OX0.bT-ChM7yy1RQtNgwcKU2um8EUoUEzQXErLrFD3ovhrk