@baseUrl = http://localhost:3000/api

###
# @name login user
POST {{baseUrl}}/admin/login
Content-Type: application/json

{
    "username": "admin",
    "password": "nxthanh@"
}

###
# @name create user
POST {{baseUrl}}/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU0NjgxNn0.f_VA_0nK2rnKBXD81hjCUTW3H38qGELgXQXK8tWrE_Y

{
    "id": "22323252325",
    "phoneNumber": "0631567899",
    "fullName": "user 3",
    "address": "address 3"
}

###
# @name Get all users

GET {{baseUrl}}/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU0NjgxNn0.f_VA_0nK2rnKBXD81hjCUTW3H38qGELgXQXK8tWrE_Y

###
# @name Get user by id

GET {{baseUrl}}/user/6364bef8d022442b874e59f7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU0NjgxNn0.f_VA_0nK2rnKBXD81hjCUTW3H38qGELgXQXK8tWrE_Y

###
# @name update user

PUT {{baseUrl}}/user/6364bef8d022442b874e59f7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU0NjgxNn0.f_VA_0nK2rnKBXD81hjCUTW3H38qGELgXQXK8tWrE_Y

{
    "fullName": "nguyen 1",
    "address": "hai phong"
}

###
# @name delete user

DELETE {{baseUrl}}/user/6364bef8d022442b874e59f7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU0NjgxNn0.f_VA_0nK2rnKBXD81hjCUTW3H38qGELgXQXK8tWrE_Y


###
# @name create place
POST {{baseUrl}}/place
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRlNDYwYjYzYTU2MzJmMzUwNzI1MCIsImlhdCI6MTY2NzU1NjQ0OH0.FGLRw_2Wu2iXW3L4rdDqC6Sh3YG0A48XKEM7OUudYeQ

{
    "name": "pho co",
    "address": "ha noi"
}


###
# @name Get all place

GET {{baseUrl}}/place
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU1NzM2NH0.uD7uvsr9Df5xe4y-w9TSaav8WWC3KbsoB23Pu0cVEuU

###
# @name Get place by id

GET {{baseUrl}}/place/6364e4ed2f48fa34e7be8d4e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU1NzM2NH0.uD7uvsr9Df5xe4y-w9TSaav8WWC3KbsoB23Pu0cVEuU

###
# @name update place

PUT {{baseUrl}}/place/6364e4ed2f48fa34e7be8d4e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU1NzM2NH0.uD7uvsr9Df5xe4y-w9TSaav8WWC3KbsoB23Pu0cVEuU

{
    "name": "ho tay",
    "address": "ha noi"
}


###
# @name Get delete by id

DELETE  {{baseUrl}}/place/6364ec516b7c3bbf70973c02
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjRiZWE3ZDAyMjQ0MmI4NzRlNTllYyIsImlhdCI6MTY2NzU1NzM2NH0.uD7uvsr9Df5xe4y-w9TSaav8WWC3KbsoB23Pu0cVEuU
